export const tennisPlayers = [
  {
    id: 1,
    name: "Roger Federer",
    link: "https://en.wikipedia.org/wiki/Roger_Federer",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Novak Djokovic",
        score: "6-4, 7-6(3), 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Rafael Nadal",
        score: "7-5, 6-4, 6-7(2), 7-6(5)",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Andy Murray",
        score: "6-3, 7-6(4), 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Novak Djokovic",
        score: "7-6(6), 6-4, 6-3",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Rafael Nadal",
        score: "7-6(5), 6-4, 6-7(3), 6-3",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-3, 6-2",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Novak Djokovic",
        score: "6-4, 6-3, 6-7(2), 7-6(5)",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Stefanos Tsitsipas",
        score: "6-2, 6-4, 6-1",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Andy Murray",
        score: "7-5, 6-4, 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Novak Djokovic",
        score: "6-4, 6-3, 7-6(4)",
      },
    ],
  },
  {
    id: 2,
    name: "Rafael Nadal",
    link: "https://en.wikipedia.org/wiki/Rafael_Nadal",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Novak Djokovic",
        score: "6-4, 6-3, 6-2",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Roger Federer",
        score: "7-5, 6-4, 6-7(2), 7-6(5)",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Andy Murray",
        score: "6-2, 6-4, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Novak Djokovic",
        score: "7-6(6), 6-4, 6-3",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Roger Federer",
        score: "7-6(5), 6-4, 6-7(3), 6-3",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-3, 6-2",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Novak Djokovic",
        score: "6-4, 6-3, 6-7(2), 7-6(5)",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Stefanos Tsitsipas",
        score: "6-2, 6-4, 6-1",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Andy Murray",
        score: "7-5, 6-4, 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Roger Federer",
        score: "6-4, 6-3, 7-6(4)",
      },
    ],
  },
  {
    id: 3,
    name: "Novak Djokovic",
    link: "https://en.wikipedia.org/wiki/Novak_Djokovic",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Roger Federer",
        score: "4-6, 7-6(3), 6-3, 6-2",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Rafael Nadal",
        score: "6-4, 6-3, 6-2",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Andy Murray",
        score: "7-5, 6-4, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Roger Federer",
        score: "6-7(6), 6-4, 7-5, 7-6(4)",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Rafael Nadal",
        score: "6-4, 6-3, 7-6(5)",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-2, 6-3",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Roger Federer",
        score: "7-6(5), 6-4, 6-3",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Stefanos Tsitsipas",
        score: "6-3, 6-2, 7-6(2)",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Andy Murray",
        score: "6-2, 6-3, 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Roger Federer",
        score: "6-4, 6-3, 7-6(4)",
      },
    ],
  },
  {
    id: 4,
    name: "Serena Williams",
    link: "https://en.wikipedia.org/wiki/Serena_Williams",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Maria Sharapova",
        score: "6-3, 6-2",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Naomi Osaka",
        score: "7-5, 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Venus Williams",
        score: "6-4, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Simona Halep",
        score: "6-2, 6-1",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Victoria Azarenka",
        score: "6-3, 6-4",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Angelique Kerber",
        score: "7-5, 6-4",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Ashleigh Barty",
        score: "6-4, 7-6(3)",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Simona Halep",
        score: "6-2, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Venus Williams",
        score: "6-2, 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Naomi Osaka",
        score: "6-3, 6-4",
      },
    ],
  },
  {
    id: 5,
    name: "Venus Williams",
    link: "https://en.wikipedia.org/wiki/Venus_Williams",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Serena Williams",
        score: "3-6, 7-5, 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Simona Halep",
        score: "6-4, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Maria Sharapova",
        score: "7-6(4), 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Angelique Kerber",
        score: "6-2, 6-4",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-3, 6-4",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Victoria Azarenka",
        score: "6-4, 7-5",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Ashleigh Barty",
        score: "6-3, 6-4",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Simona Halep",
        score: "7-5, 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Maria Sharapova",
        score: "6-2, 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Serena Williams",
        score: "7-5, 6-3",
      },
    ],
  },
  {
    id: 6,
    name: "Andy Murray",
    link: "https://en.wikipedia.org/wiki/Andy_Murray",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Roger Federer",
        score: "4-6, 3-6, 6-4, 7-6(5), 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Rafael Nadal",
        score: "2-6, 6-7(2), 7-5, 6-4, 8-6",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Novak Djokovic",
        score: "3-6, 7-6(4), 6-4, 4-6, 7-5",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Roger Federer",
        score: "7-5, 6-3, 6-7(6), 6-4",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Rafael Nadal",
        score: "6-4, 6-3, 6-2",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-3, 6-4",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Novak Djokovic",
        score: "6-7(4), 6-4, 7-5, 6-2",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Stefanos Tsitsipas",
        score: "7-6(3), 6-3, 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Roger Federer",
        score: "6-3, 7-6(2), 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Novak Djokovic",
        score: "4-6, 6-7(5), 7-5, 6-4, 10-8",
      },
    ],
  },
  {
    id: 7,
    name: "Maria Sharapova",
    link: "https://en.wikipedia.org/wiki/Maria_Sharapova",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Serena Williams",
        score: "6-3, 6-2",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Venus Williams",
        score: "7-6(4), 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Simona Halep",
        score: "6-4, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Angelique Kerber",
        score: "6-2, 6-4",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-3, 6-4",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Victoria Azarenka",
        score: "6-4, 7-5",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Ashleigh Barty",
        score: "6-3, 6-4",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Simona Halep",
        score: "7-5, 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Venus Williams",
        score: "6-2, 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Serena Williams",
        score: "7-5, 6-3",
      },
    ],
  },
  {
    id: 8,
    name: "Naomi Osaka",
    link: "https://en.wikipedia.org/wiki/Naomi_Osaka",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Serena Williams",
        score: "7-5, 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Venus Williams",
        score: "6-3, 6-2",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Ashleigh Barty",
        score: "6-4, 7-6(3)",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Simona Halep",
        score: "6-3, 6-2",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-2, 6-3",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Victoria Azarenka",
        score: "7-5, 6-4",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Maria Sharapova",
        score: "6-4, 6-3",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Angelique Kerber",
        score: "6-3, 6-2",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Ashleigh Barty",
        score: "7-6(4), 6-3",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Serena Williams",
        score: "6-3, 7-5",
      },
    ],
  },
  {
    id: 9,
    name: "Steffi Graf",
    link: "https://en.wikipedia.org/wiki/Steffi_Graf",
    games: [
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Serena Williams",
        score: "6-4, 6-2",
      },
      {
        tournament: "Australian Open",
        year: 2023,
        opponent: "Martina Navratilova",
        score: "7-5, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Monica Seles",
        score: "6-3, 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 2022,
        opponent: "Chris Evert",
        score: "6-2, 6-1",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Serena Williams",
        score: "6-4, 6-3",
      },
      {
        tournament: "US Open",
        year: 2021,
        opponent: "Martina Navratilova",
        score: "6-3, 6-2",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Monica Seles",
        score: "6-4, 7-6(3)",
      },
      {
        tournament: "French Open",
        year: 2021,
        opponent: "Chris Evert",
        score: "6-2, 6-1",
      },
      {
        tournament: "Wimbledon",
        year: 2020,
        opponent: "Martina Navratilova",
        score: "7-6(2), 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2020,
        opponent: "Serena Williams",
        score: "6-3, 6-2",
      },
    ],
  },
  {
    id: 10,
    name: "Pete Sampras",
    link: "https://en.wikipedia.org/wiki/Pete_Sampras",
    games: [
      {
        tournament: "Australian Open",
        year: 2000,
        opponent: "Andre Agassi",
        score: "6-4, 6-3, 6-4",
      },
      {
        tournament: "Australian Open",
        year: 2000,
        opponent: "Boris Becker",
        score: "7-6(4), 6-4, 6-3",
      },
      {
        tournament: "Wimbledon",
        year: 1999,
        opponent: "Patrick Rafter",
        score: "6-3, 7-6(5), 6-4",
      },
      {
        tournament: "Wimbledon",
        year: 1999,
        opponent: "Goran Ivanisevic",
        score: "6-4, 7-5, 6-3",
      },
      {
        tournament: "US Open",
        year: 1998,
        opponent: "Andre Agassi",
        score: "6-4, 6-3, 6-2",
      },
      {
        tournament: "US Open",
        year: 1998,
        opponent: "Michael Chang",
        score: "7-6(3), 6-4, 6-2",
      },
      {
        tournament: "French Open",
        year: 1997,
        opponent: "Yevgeny Kafelnikov",
        score: "6-3, 6-2, 6-4",
      },
      {
        tournament: "French Open",
        year: 1997,
        opponent: "Jim Courier",
        score: "6-4, 6-3, 7-6(2)",
      },
      {
        tournament: "Wimbledon",
        year: 1996,
        opponent: "Goran Ivanisevic",
        score: "6-3, 6-7(4), 7-6(2), 6-4",
      },
      {
        tournament: "Australian Open",
        year: 1996,
        opponent: "Boris Becker",
        score: "7-6(5), 6-4, 6-3",
      },
    ],
  },
];
